# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTesteprefeitura():
    def setup_method(self, method):
        self.driver = webdriver.Chrome('C:/Users/SAFIRA/PycharmProjects/guia-iptu/drivers/chrome96/chromedriver.exe')
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_testeprefeitura(self):
        self.driver.get("https://prefeitura.pbh.gov.br/")
        self.driver.set_window_size(1280, 725)
        self.driver.find_element(By.ID, "edit-search-api-fulltext").click()
        self.driver.find_element(By.ID, "edit-search-api-fulltext").send_keys("guia iptu")
        self.driver.find_element(By.CSS_SELECTOR, ".better_search").click()
        assert self.driver.find_element(By.LINK_TEXT, "IPTU").text == "IPTU"
        assert self.driver.find_element(By.LINK_TEXT, "Dívida Ativa").text == "Dívida Ativa"